### ISSUE TITLE
v0.7: can't set the default for `bool` field

### ISSUE THREAD

**Issue by MaxVerevkin** [idanarye/rust-smart-default#13]
```rust
use smart_default::SmartDefault;

fn main() {
    dbg!(S::default());
}

#[derive(Debug, SmartDefault)]
struct S {
    #[default(1)] // works
    i: i32,
    #[default(true)] // error: Expected single value in #[default(...)]
    b: bool,
}
```

**Comment by tyranron** [comment]
Have similar error with `#[default(Coloring::Auto)]` attribute.

**Comment by tyranron** [comment]
The regression popped up [here](https://github.com/idanarye/rust-smart-default/pull/11/files#diff-f9ff3818e2677de63993b411e434e923d88df57a6b89540d915ee90ada58cc98R44-L45), the error migrated to another `if` branch, causing to fire early.
